### ISSUE TITLE
Prevents scroll when using smart zoom on macOS

### ISSUE THREAD

**Issue by oskar-gmerek** [janosh/svelte-toc#22]
Hi,

When using smart zoom (double-taped mouse) svelte-toc prevents scrolling down to the bottom of the page. The scroll position jumps up when the active header should change instead of scrolling down and changing the active header in svelte-toc.

https://user-images.githubusercontent.com/53402105/189860612-ca691cce-c878-4573-8e13-0c16083b1801.mov

I also find out, that if I do not wrap <Toc /> with a fixed position wrapper, then svelte-toc prevents scrolling the page more than the height of the ToC component.

**Comment by janosh** [comment]
Oops, that's embarrassing. Thanks for reporting! 👍
