### ISSUE TITLE
Component persisting on page change when not required

### ISSUE THREAD

**Issue by thedivtagguy** [janosh/svelte-toc#3]
Thank you for a great plugin!
I have tried implementing it on my website, but there seems to be a weird issue. When I switch from a page that needs the ToC to a one that doesn't, there is a brief moment where a Table of Contents for the latter page is loaded before the component disappears. The lag is noticeable. 

You can try it by going to [this](https://61cd547ade553b00098be516--thedivtagguy2.netlify.app) page and navigating to the homepage.

Recording:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/6006888/147729142-cb20f4af-c62d-4857-a089-2dc5bd3f1aa7.gif)

I have included my component [like this](https://github.com/thedivtagguy/website2/blob/main/src/components/ProjectsPage.svelte#L70)

Any thoughts on why this might be happening?

**Comment by janosh** [comment]
Thanks for reporting! 👍 Should be fixed in [v0.1.11](https://www.npmjs.com/package/svelte-toc/v/0.1.11). Could you give that a try?

**Comment by thedivtagguy** [comment]
Thank you for the prompt patch, this seems to have fixed it!
