### ISSUE TITLE
Component insists on starting at full height above the text

### ISSUE THREAD

**Issue by aegonwolf** [janosh/svelte-toc#35]
Thank you for this great tool and plugin!
I've played around with it quite a long time as I am trying to use it for an interactive version of my bachelor thesis ToC.

I have a small issue that I haven't been able to fix in the past few hours and would love your input.
When I enter the component like so:

```svelte
<Toc
  desktop = {true},
  headingSelector = {":is(h1, h2):not(.toc-exclude)"}
  --toc-desktop-max-width = "300px";
  />
```
It first starts by using up its full height above the actual content. 

![wnzXSlr](https://user-images.githubusercontent.com/30958850/219818475-8313ee29-87b6-4f7a-ae66-21cc7b5411be.png)

This is actually also the case for the example code provided:

```svelte
<Toc
  --toc-desktop-aside-margin="10em 0 0 0"
  --toc-desktop-sticky-top="3em"
  --toc-desktop-width="15em"
/>
```
Though I am guessing I am too newbie to get it right.

I can make it work by setting it in an `absolute` positioned div, but then it becomes unsticky.
Any advice on how to correctly do this would be greatly appreciated, thank you so much either way for this component!

**Comment by janosh** [comment]
@aegonwolf Thanks for the feedback, glad you like it!

It's up to the developer to position the ToC where/how you want. If you want `position: sticky` without taking up space on the page (like `position: absolute`) you can give the parent element `position: absolute` and set an explicit height. You could also set `display: flex;` on the parent container to have the ToC and content side-by-side 'naturally'.

**Comment by janosh** [comment]
Here's a minimal [REPL](https://svelte.dev/repl/e292ff8935dc4f5d97e5373f9f611c1b) showing the `display: flex;` way.

**Comment by aegonwolf** [comment]
Dear @janosh thank you so much! This repl works, though, I have to render the toc after the content then right?
This has indeed worked, though again it's just a preference, I'd like to render it on the left. 
When I have the parent element as absolute it won't be sticky anymore.
I'm also using tailwind btw.

**Comment by janosh** [comment]
Cool, I'll close this as resovled then.
