### ISSUE TITLE
Svelte-toc interferes with other anchor links in the document

### ISSUE THREAD

**Issue by aegonwolf** [janosh/svelte-toc#36]
Hi, 
I think it's possible that svelte-toc interferes with other anchor links and smooth scrolling to them in the document.

I add it inside a `<body class='flex main-bg'>`  like so:
```
<div class='w-50'>
    <div
  on:click="{() => showToc = !showToc}" 
  class='main-bg w-9 h-9 m-2 hover:cursor-pointer sticky top-0'>
      <svg fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"></path>
      </svg>
  </div>
  {#if showToc}
  <Toc
    title = {"Table of Contents"},
    desktop = {true},
    headingSelector = {":is(h1, h2, h3):not(.toc-exclude)"}
    --toc-desktop-max-width = "20em"/>
    {/if}
</div>
```

The former is just an icon-burger button.

If I comment out the above the other anchor links work as expected (smooth scroll to them).
I am using Svelte and Tailwind.

For me this isn't such a big deal due to the nature of my anchor links (just references and I have them on hover anyway) but I thought you might want to be aware of it.

I can provide a link to the document to see it live if you like.

Cheers, and thanks again for this component, it made my project so much nicer.

**Comment by janosh** [comment]
Thanks for the bug report. I think I remember seeing this as well at some point. Haven't had time to dig into it yet so can't offer a quick fix. A link to your site to see the problem in the wild would be great! 👍

**Comment by aegonwolf** [comment]
> Thanks for the bug report. I think I remember seeing this as well at some point. Haven't had time to dig into it yet so can't offer a quick fix. A link to your site to see the problem in the wild would be great! 👍

I think it's browser specific, works almost fine with firefox (sometimes it goes to the wrong anchor, when I turn it off it works again in FF). In Chrome/Edge this always doesn't work for me.

Mondaystats.com/thesis
the references i.e. `[18]` are the anchor links that I have. 

Cheers,

Oli

**Comment by janosh** [comment]
Yes, this is the behavior I remember seeing! I think making the scroll handler `passive` might solve this problem. Is the code public? If not, could you edit the `Toc.svelte` in your `node_modules` in-place as follows?

```diff
<svelte:window
  bind:innerWidth={window_width}
-  on:scroll={set_active_heading}
+  on:scroll|passive={set_active_heading}
  on:click={close}
/>
```

Be sure to restart the dev server. If you try that, let me know if it helps.

**Comment by janosh** [comment]
Also, great work on that thesis! Very impressive. 👍

**Comment by janosh** [comment]
Actually, this won't work. No need to try the `passive` modifier. I remember looking into this before. This appears to be a bug in Chromium that's been reported many times [on SO](https://stackoverflow.com/q/49318497) and in the Chromium issue tracker as well:

- https://bugs.chromium.org/p/chromium/issues/detail?id=1121151
- https://bugs.chromium.org/p/chromium/issues/detail?id=1043933
- https://bugs.chromium.org/p/chromium/issues/detail?id=833617

which might explain why it's working in FF. Sadly no response from the Chromium devs yet.

**Comment by janosh** [comment]
2 workarounds:

1. remove
    ```css
    html {
      scroll-behavior: smooth;
    }
    ```
1. Pass `keepActiveTocItemInView={false}` to `<Toc />`.

**Comment by aegonwolf** [comment]
@janosh thanks a lot for this (and the compliment :-)) I'll try with removing smooth scrolling, I have it through tailwind, and the second option too, I'll update if this works.

**Comment by janosh** [comment]
No need to remove smooth scrolling anymore. If you look at https://github.com/janosh/svelte-toc/pull/37, I changed `svelte-toc` to wait for any page scrolling to finish before scrolling the active ToC item into view. To fix your problem, try just updating `svelte-toc` to latest.

**Comment by aegonwolf** [comment]
> No need to remove smooth scrolling anymore. If you look at #37, I changed `svelte-toc` to wait for any page scrolling to finish before scrolling the active ToC item into view. To fix your problem, try just updating `svelte-toc` to latest.

That's awesome, thank you so much!
