### ISSUE TITLE
[Question]TypeScript support

### ISSUE THREAD

**Issue by lym8356** [janosh/svelte-toc#42]
Hi, does this library support TypeScript?

I am getting errors when I import this library in my TypeScript project.

**Comment by janosh** [comment]
Yes, TS is supported. Could you be more specific? What error are you seeing?

**Comment by lym8356** [comment]
It says "Cannot find module 'svelte-toc' or its corresponding type declarations."
I have seen this error before when I tried to use a package that does not support typescript, or I forgot to install its @type package.

**Comment by janosh** [comment]
Sounds like it might be the same problem as https://github.com/janosh/svelte-multiselect/issues/233. If so, the recommended solution is also the same. Either update to typescript v5 and set your module resolution to "bundler" or downgrade to before this package version migrated to svelte-package v2.

**Comment by lym8356** [comment]
After I set my module resolution to bundler, it is working without problem. Thank you for your help!
